id: IE2C338E3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:02:10+00:00'
last_modified: '2022-06-07T22:20:07.471264+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1646
  title: མ་གཅིག་ལབ་ཀྱི་སྒྲོན་མའི་རྣམ་ཐར་དང་གཅོད་ཀྱི་ཆོས་སྐོར་མ་འོངས་ལུང་བསྟན་བཅས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4FA1:
      image_group_id: I1KG1652
      title: ''
      total_pages: 430
      order: 1
      base_file: 4FA1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
