id: P004366
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1646
  title: མ་གཅིག་ལབ་ཀྱི་སྒྲོན་མའི་རྣམ་ཐར་དང་གཅོད་ཀྱི་ཆོས་སྐོར་མ་འོངས་ལུང་བསྟན་བཅས་པ
  author: ''
  volumes:
    33402a54ee6a4451a2338054b3da1cec:
      image_group_id: I1KG1652
      title: ''
      volume_number: 1
      total_pages: 430
